[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[test]
upgradeable = true

[programs.localnet]
predictory = "Hb2nMQLGRK1htQqMbDBU6ejjUNmR2X2UHJDy3hEXyjG7"

[programs.devnet]
predictory = "Hb2nMQLGRK1htQqMbDBU6ejjUNmR2X2UHJDy3hEXyjG7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest"
