name: SMC Rust CI

on:
  push:
    paths:
      - 'smc/**'
      - '.github/workflows/smc-ci.yml'
  pull_request:
    paths:
      - 'smc/**'
      - '.github/workflows/smc-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smc
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Install dependencies
        run: cargo fetch
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
      - name: Run tests
        run: cargo test --all
